[project]
name = "ferminal"
version = "1.4.2"
description = "Custom Wrapper CLI to make your work faster"
authors = [
    {name="RangS"}
]

dependencies = [
    "colorama",
    "prompt_toolkit",
]

[project.scripts]
ferminal = "ferminal.main:main"

[build-system]
requires = [
    "setuptools>=61",
    "wheel"
]
build-backend = "setuptools.build_meta"